// name = "eduaid-whatsapp-proxy"
// main = "src/worker.ts"
// compatibility_date = "2024-06-01"
// [vars]
// TWILIO_ACCOUNT_SID = "ACxxxxxxxx..."
// TWILIO_AUTH_TOKEN = "..."
// TWILIO_FROM = "whatsapp:+14155238886"